### ISSUE TITLE
Error running the script for Kannada

### ISSUE THREAD

**Issue by omshivaprakash** [tshrinivasan/OCR4wikisource#1]
techfiz:~/projects/OCR4wikisource$ python do_ocr.py
Downloading the file %E0%B2%9A%E0%B2%BF%E0%B2%A4%E0%B3%8D%E0%B2%B0:Duurada_Nakshhatra.pdf
[################################] 12/12 - 00:00:00
Aligining the Pages of PDF file. 

error: cannot recognize version marker
warning: trying to repair broken xref
warning: assert: val does not exist for key (Type)
warning: assert: val does not exist for key (Pages)
warning: object out of range (0 0 R); xref size 1
Spliting the PDF into single pages. 

Error: Unexpected Exception in open_reader()
Unhandled Java Exception in main():
java.lang.NullPointerException
   at gnu.gcj.runtime.NameFinder.lookup(libgcj.so.15)
   at java.lang.Throwable.getStackTrace(libgcj.so.15)
   at java.lang.Throwable.stackTraceString(libgcj.so.15)
   at java.lang.Throwable.printStackTrace(libgcj.so.15)
   at java.lang.Throwable.printStackTrace(libgcj.so.15)
Joining the PDF files ...
Creating a folder in Google Drive to upload files 
Folder Name : temp-2015-12-20-13-10-53
sh: 1: gdmkdir.py: not found
 Moving all temp files to temp-2015-12-20-13-10-53
mv: target 'temp-2015-12-20-13-10-53' is not a directory

Done. Check the text files start with text_for_page_ 
# 

Looks like I have some version mismatch issues on the system. Let me know if there is any quick work around.

**Comment by tshrinivasan** [comment]
What is the File URL your are downloading?

Let me give a try.

> sh: 1: gdmkdirpy: not found

This error show that gdmkdirpy is not available.

Did you edit that line?
because it should be as gdmkdir.py

check the dot.

Did you install gdcmdtools package?

2015-12-20 13:14 GMT+05:30 Omshivaprakash H L notifications@github.com:

> techfiz:~/projects/OCR4wikisource$ python do_ocrpy
> Downloading the file
> %E0%B2%9A%E0%B2%BF%E0%B2%A4%E0%B3%8D%E0%B2%B0:Duurada_Nakshhatrapdf
> [################################] 12/12 - 00:00:00
> Aligining the Pages of PDF file
> 
> error: cannot recognize version marker
> warning: trying to repair broken xref
> warning: assert: val does not exist for key (Type)
> warning: assert: val does not exist for key (Pages)
> warning: object out of range (0 0 R); xref size 1
> Spliting the PDF into single pages
> 
> Error: Unexpected Exception in open_reader()
> Unhandled Java Exception in main():
> javalangNullPointerException
> at gnugcjruntimeNameFinderlookup(libgcjso15)
> at javalangThrowablegetStackTrace(libgcjso15)
> at javalangThrowablestackTraceString(libgcjso15)
> at javalangThrowableprintStackTrace(libgcjso15)
> at javalangThrowableprintStackTrace(libgcjso15)
> Joining the PDF files
> Creating a folder in Google Drive to upload files
> Folder Name : temp-2015-12-20-13-10-53
> sh: 1: gdmkdirpy: not found
> Moving all temp files to temp-2015-12-20-13-10-53
> mv: target 'temp-2015-12-20-13-10-53' is not a directory
> 
> Done Check the text files start with text_for_page_
> 
> Looks like I have some version mismatch issues on the system Let me know
> if there is any quick work around
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tshrinivasan/OCR4wikisource/issues/1.

## 

Regards,
T.Shrinivasan

My Life with GNU/Linux : http://goinggnu.wordpress.com
Free E-Magazine on Free Open Source Software in Tamil : http://kaniyam.com

Get Free Tamil Ebooks for Android, iOS, Kindle, Computer :
http://FreeTamilEbooks.com

**Comment by tshrinivasan** [comment]
You should give the real Full URL of the PDF file.

I think, this is the file you are trying.

https://upload.wikimedia.org/wikipedia/commons/4/4c/Duurada_Nakshhatra.pdf

Got the URL for the file from 
https://kn.wikisource.org/wiki/ಚಿತ್ರ:Duurada_Nakshhatra.pdf

**Comment by omshivaprakash** [comment]
https://kn.wikisource.org/wiki/%E0%B2%9A%E0%B2%BF%E0%B2%A4%E0%B3%8D%E0%B2%B0:Duurada_Nakshhatra.pdf - this is what I'm using. I haven't edited the file though.

**Comment by tshrinivasan** [comment]
Use the correct url of the file.

https://upload.wikimedia.org/wikipedia/commons/4/4c/Duurada_Nakshhatra.pdf

**Comment by tshrinivasan** [comment]
Does giving correct URL help to run the program? @omshivaprakash

**Comment by omshivaprakash** [comment]
page download works but google upload seem to be an issue.

$ python do_ocr.py

Downloading the file Duurada_Nakshhatra.pdf

[################################] 12769/12769 - 00:00:13
Aligining the Pages of PDF file. 

Spliting the PDF into single pages. 

Joining the PDF files ...

Creating a folder in Google Drive to upload files 

Folder Name : temp-2015-12-20-14-58-33

sh: 1: gdmkdir.py: not found

uploading page_00001.pdf to google Drive 

Traceback (most recent call last):
  File "do_ocr.py", line 130, in <module>
    command = "gdput.py -t ocr -f   " +  drive_folder_id + " "  + pdf_file + " | tee " + pdf_file.split('.')[0] + ".log"
NameError: name 'drive_folder_id' is not defined

**Comment by tshrinivasan** [comment]
gdmkdir.py is added very recently in gdcmdtools. (5 days ago)
https://github.com/tienfuc/gdcmdtools/issues/67

download the recent zip file of gdcmdtools from
https://github.com/tienfuc/gdcmdtools

extract it.

run the following commands.

cd gdcmdtools
sudo python setup.py install

This will install the latest gdcmdtools.

Then, run the do_ocr.py

I have added the feature to add suffix of non-arabic, indian numerals to the Page names for various indian languages.
Get the new zip from https://github.com/tshrinivasan/OCR4wikisource and use it.

**Comment by omshivaprakash** [comment]
I pulled the gdcmdtools from git. Let me try agian

**Comment by omshivaprakash** [comment]
I had few files in gdcdmtools. Removed them and pulled the update. 

==Here is the new error==
Traceback (most recent call last):
  File "/usr/local/bin/gdmkdir.py", line 4, in <module>
    **import**('pkg_resources').run_script('gdcmdtools==1.0', 'gdmkdir.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools-1.0-py2.7.egg/EGG-INFO/scripts/gdmkdir.py", line 65, in <module>

  File "build/bdist.linux-x86_64/egg/gdcmdtools/mkdir.py", line 41, in **init**
  File "build/bdist.linux-x86_64/egg/gdcmdtools/base.py", line 47, in get_drive_service
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 196, in build
    cache)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 242, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 596, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.1-py2.7.egg/httplib2/__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.1-py2.7.egg/httplib2/__init__.py", line 1350, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.1-py2.7.egg/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.1-py2.7.egg/httplib2/__init__.py", line 1036, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "/usr/local/lib/python2.7/dist-packages/httplib2-0.9.1-py2.7.egg/httplib2/**init**.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "/usr/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 520, in __init__
    self._context.load_verify_locations(ca_certs)
IOError: [Errno 13] Permission denied

uploading page_00001.pdf to google Drive 

Traceback (most recent call last):
  File "do_ocr.py", line 130, in <module>
    command = "gdput.py -t ocr -f   " +  drive_folder_id + " "  + pdf_file + " | tee " + pdf_file.split('.')[0] + ".log"
NameError: name 'drive_folder_id' is not defined

**Comment by omshivaprakash** [comment]
Does that mean I have not authenticated gdcmdtools properly? Let me check that as well.

**Comment by omshivaprakash** [comment]
# I had to run python do_ocr.py as with sudo to make this work!

Creating a folder in Google Drive to upload files 
Folder Name : temp-2015-12-20-15-39-56
id: 0B8IZF943h4S0S0I1eU9TRkFGYTg
driver view: https://drive.google.com/drive/folders/0B8IZF943h4S0S0I1eU9TRkFGYTg
folder view: https://docs.google.com/folderview?id=0B8IZF943h4S0S0I1eU9TRkFGYTg&usp=drivesdk
uploading page_00001.pdf to google Drive 
Uploading file: page_00001.pdf
Completed!  
id: 1HtV_zn4IdGvngN3eT-c_6p4cM18hKgMd8yx3cIVJj3k
drive url: https://docs.google.com/document/d/1HtV_zn4IdGvngN3eT-c_6p4cM18hKgMd8yx3cIVJj3k/edit?usp=drivesdk
text/html: https://docs.google.com/feeds/download/documents/export/Export?id=1HtV_zn4IdGvngN3eT-c_6p4cM18hKgMd8yx3cIVJj3k&exportFormat=html
application/pdf: https://docs.google.com/feeds/download/documents/export/Export?id=1HtV_zn4IdGvngN3eT-c_6p4cM18hKgMd8yx3cIVJj3k&exportFormat=pdf
application/vnd.openxmlformats-officedocument.wordprocessingml.document: https://docs.google.com/feeds/download/documents/export/Export?id=1HtV_zn4IdGvngN3eT-c_6p4cM18hKgMd8yx3cIVJj3k&exportFormat=docx
application/vnd.oasis.opendocument.text: https://docs.google.com/feeds/download/documents/export/Export?id=1HtV_zn4IdGvngN3eT-c_6p4cM18hKgMd8yx3cIVJj3k&exportFormat=odt
application/rtf: https://docs.google.com/feeds/download/documents/export/Export?id=1HtV_zn4IdGvngN3eT-c_6p4cM18hKgMd8yx3cIVJj3k&exportFormat=rtf

# text/plain: https://docs.google.com/feeds/download/documents/export/Export?id=1HtV_zn4IdGvngN3eT-c_6p4cM18hKgMd8yx3cIVJj3k&exportFormat=txt

Working now.

**Comment by tshrinivasan** [comment]
Did you run  'sudo python setup.py install' for gdcmdtools?
check the history.

For me do_ocr.py runs as normal user. but installed gdcmdtools as sudo.

Thanks for the research and reporting.

Share your suggestions to improve.

**Comment by omshivaprakash** [comment]
yes, the gdcmdtools were installed with sudo. gdauth.py also worked only as sudo for me. That was the hint used to run do_ocr.py as sudo. 

One quick suggestion. Please do create a temporary folder for the PDF downloads and split operations before hand so that it won't make the working folder crowded. Also, book file name itself can be used as the working folder name.

**Comment by omshivaprakash** [comment]
In README - mediawiki_uploader.py needs to be changed to mediawiki-uploader.py or file needs to be renamed.

**Comment by tshrinivasan** [comment]
Renamed the file. Thanks. Closing this issue.
