### ISSUE TITLE
Upload folder not created

### ISSUE THREAD

**Issue by ravidreams** [tshrinivasan/OCR4wikisource#10]
File - https://upload.wikimedia.org/wikipedia/commons/7/7e/Indradhanu%2C_Akhi_O_Kabitar_Dirgha_JIban.pdf

OR WS URL - https://or.wikisource.org/wiki/%E0%AC%B8%E0%AD%82%E0%AC%9A%E0%AD%80:Indradhanu,_Akhi_O_Kabitar_Dirgha_JIban.pdf

File downloaded and split. Upload folder not created in Google drive. 

Error log:

(many repeat messages like this regarding pdf and then finally)

pdfunite version 0.24.5
Copyright 2005-2013 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
Usage: pdfunite [options] <PDF-sourcefile-1>..<PDF-sourcefile-n> <PDF-destfile>
  -v             : print copyright and version info
  -h             : print usage information
  -help          : print usage information
  --help         : print usage information
  -?             : print usage information

Creating a folder in Google Drive to upload files 

Folder Name : OCR-Indradhanu,_Akhi_O_Kabitar_Dirgha_JIban.pdf-temp-2015-12-28-22-11-48

id: 0B9amQol3ByIjNUplYl9IRVlNWVE
drive view: https://drive.google.com/drive/folders/0B9amQol3ByIjNUplYl9IRVlNWVE
folder view: https://docs.google.com/folderview?id=0B9amQol3ByIjNUplYl9IRVlNWVE&usp=drivesdk

Moving all temp files to OCR-Indradhanu,_Akhi_O_Kabitar_Dirgha_JIban.pdf-temp-2015-12-28-22-11-48

mv: target ‘OCR-Indradhanu,_Akhi_O_Kabitar_Dirgha_JIban.pdf-temp-2015-12-28-22-11-48’ is not a directory

Done. Check the text files start with text_for_page_

**Comment by ravidreams** [comment]
Just reporting that the same issue was reproduced from another system too.

**Comment by tshrinivasan** [comment]
using the version 1.26, for me, the google drive folder is created and files are uploading there.

Check with the latest version and share the results.

**Comment by tshrinivasan** [comment]
all the 92 pages uploaded fine and got the 92 text files.

**Comment by ravidreams** [comment]
Same error still. Tried with version Version 1.28

**Comment by ravidreams** [comment]
Same error with 1.29:

mv: target ‘OCR-গীতি-কবিতা.pdf-temp-2016-01-04-21-25-57’ is not a directory

Sending log file by mail.

**Comment by ravidreams** [comment]
Attaching log for another test.
[do_ocr_2016-01-04-21-41-28_log.txt](https://github.com/tshrinivasan/OCR4wikisource/files/77402/do_ocr_2016-01-04-21-41-28_log.txt)

**Comment by tshrinivasan** [comment]
Are you running ubuntu 12.04?

I think there is some issue with pdfunite in ubuntu 12.04

can you run this and share the output?
pdfunite pg_0001.pdf page_00001.pdf

**Comment by tshrinivasan** [comment]
Do you have many pdf files start with page_ ?

delete all the pdf files start with page.

rm page*.pdf

and run 

python do_ocr.py 

again.

**Comment by tshrinivasan** [comment]
can replicate the issue in ubuntu 12.04.

Will fix soon.

**Comment by jayantanth** [comment]
Actually Upload folder have been created all time, I have checked that all created folders are now in my google drive trash.

NB: I have not deleted manually

**Comment by jayantanth** [comment]
![screenshot from 2016-01-05 02 35 31](https://cloud.githubusercontent.com/assets/1370149/12100450/0a755996-b355-11e5-880e-41e7931fb5c7.png)

**Comment by tshrinivasan** [comment]
Found that pdfunite in ubuntu 12.04 is operating differently from ubuntu
15.04

Added a fix for it.

Try the version 1.32

2016-01-05 2:36 GMT+05:30 Jayanta Nath notifications@github.com:

> [image: screenshot from 2016-01-05 02 35 31]
> https://cloud.githubusercontent.com/assets/1370149/12100450/0a755996-b355-11e5-880e-41e7931fb5c7.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tshrinivasan/OCR4wikisource/issues/10#issuecomment-168808653
> .

## 

Regards,
T.Shrinivasan

My Life with GNU/Linux : http://goinggnu.wordpress.com
Free E-Magazine on Free Open Source Software in Tamil : http://kaniyam.com

Get Free Tamil Ebooks for Android, iOS, Kindle, Computer :
http://FreeTamilEbooks.com

**Comment by tshrinivasan** [comment]
pdfunite available for ubuntu 12.04 seems older and different than ubuntu 15.04

Added a fix for this in 1.32

try this and share the results.

**Comment by jayantanth** [comment]
Using 1.32 Ubuntu 12.04
Successfully done do_ocr.py . :+1:   :+1:  :+1:  :+1:  :+1:

Checked on pdf and djvu file both. Working fine.

**Comment by jayantanth** [comment]
Just watched that under my script folder "\Home\OCR" all txt file available and also one more folder  "Home\OCR\OCR-Testocrbengali.djvu-temp-2016-01-05-03-07-50"  contain with txt log and pdf. The temp folder is fine for locate.

**Comment by tshrinivasan** [comment]
Yes. Those are the folders and files created by do_ocr.py program.

**Comment by tshrinivasan** [comment]
Closing this now.

Reopen if you find same issue.

**Comment by tshrinivasan** [comment]
Closing this #20 is for empty text files.
