### ISSUE TITLE
Regarding to save scan PDF files in computer instead of Wikisource upload 

### ISSUE THREAD

**Issue by pooja7795** [tshrinivasan/OCR4wikisource#108]
I want to save scanned PDF file on my computer only. Right now after scanning its uploading directly on Wikisource . Please help in that to resolve. 

Is that any change I have to make in **do_ocr.py** ??

**Comment by tshrinivasan** [comment]
delete or comment the last 4 lines in do_ocr.py, to avoid uploading to wikisource.


add # in front of those lines to comment them like below. or delete them.
if  pdf_count == result_text_count:
            logger.info("\n\nThe PDF files and result text files are equval. Now running the mediawiki_uploader.py script\n\n")
            command = "python mediawiki_uploader.py"
            os.system(command)
