### ISSUE TITLE
PDF to image is not required for reexecution of the script

### ISSUE THREAD

**Issue by tshrinivasan** [tshrinivasan/OCR4wikisource#113]
PDF to image is not required for reexecution of the script

Avoid it.

**Comment by GurlalSinghMaan** [comment]
Hello,
Shrinivasan T

I am facing this reexecution problem

the following error comes again n agian
All pdf files are not equal to jpeg fils..run again 

i run again n agian but it shows same result.

Please tell me how to do ocr without conversion of pdf to jpeg

**Comment by tshrinivasan** [comment]
Fix this with latest version.
