### ISSUE TITLE
create_dummy_files - migrate this script to python3

### ISSUE THREAD

**Issue by tha-uzhavan** [tshrinivasan/OCR4wikisource#118]
It is really very happy to use ocr4wikisource in python3. Thanks indeed. Kindly  migrate "create_dummy_files" file to python3.

**Comment by tshrinivasan** [comment]
migrated with [cb75d82](https://github.com/tshrinivasan/OCR4wikisource/commit/cb75d829a474f9004f5916ddffa40dcace7ae3cf)

**Comment by tha-uzhavan** [comment]
kindly do the change as in 528th line of do_ocr.py // Run this script again to complete OCR all the Pages// . While doing, as you told, re run the script **only** for the pages with out ocr text.
