### ISSUE TITLE
Error in Bengali Wikisource

### ISSUE THREAD

**Issue by jayantanth** [tshrinivasan/OCR4wikisource#12]
Testing file
[link](https://bn.wikisource.org/wiki/%E0%A6%9A%E0%A6%BF%E0%A6%A4%E0%A7%8D%E0%A6%B0:%E0%A6%97%E0%A7%80%E0%A6%A4%E0%A6%BF-%E0%A6%95%E0%A6%AC%E0%A6%BF%E0%A6%A4%E0%A6%BE.pdf)

jayanta@jayanta-Inspiron-3541:~$ cd ocr
bash: cd: ocr: No such file or directory
jayanta@jayanta-Inspiron-3541:~$ cd OCR
jayanta@jayanta-Inspiron-3541:~/OCR$ python do_ocr.py

Downloading the file চিত্র:গীতি-কবিতা.pdf

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[################################] 13/13 - 00:00:00
Aligining the Pages of PDF file. 

sh: 1: mutool: not found
Spliting the PDF into single pages. 

Error: Failed to open PDF file: 
   currentfile.pdf
Done.  Input errors, so no output created.
Joining the PDF files ...

Creating a folder in Google Drive to upload files 

Folder Name : OCR-চিত্র:গীতি-কবিতা.pdf-temp-2016-01-01-00-04-46

id: 0B1OpcVV-_vRSZ0dmbHBZTFI1OTg
drive view: https://drive.google.com/drive/folders/0B1OpcVV-_vRSZ0dmbHBZTFI1OTg
folder view: https://docs.google.com/folderview?id=0B1OpcVV-_vRSZ0dmbHBZTFI1OTg&usp=drivesdk

Moving all temp files to OCR-চিত্র:গীতি-কবিতা.pdf-temp-2016-01-01-00-04-46

Traceback (most recent call last):
  File "do_ocr.py", line 240, in <module>
    os.system(command)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 68-72: ordinal not in range(128)

**Comment by tshrinivasan** [comment]
Check the INSTALL file and complete the installations.

**Comment by tshrinivasan** [comment]
Share the file URL you use.

Let me try too.

**Comment by jayantanth** [comment]
https://upload.wikimedia.org/wikipedia/commons/4/44/%E0%A6%97%E0%A7%80%E0%A6%A4%E0%A6%BF-%E0%A6%95%E0%A6%AC%E0%A6%BF%E0%A6%A4%E0%A6%BE.pdf

**Comment by jayantanth** [comment]
I have followed the step by step INSTALL again,

again the the same error

jayanta@jayanta-Inspiron-3541:~/OCR$ python do_ocr.py

Downloading the file চিত্র:গীতি-কবিতা.pdf

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[################################] 13/13 - 00:00:00
Aligining the Pages of PDF file. 

sh: 1: mutool: not found
Spliting the PDF into single pages. 

Error: Failed to open PDF file: 
   currentfile.pdf
Done.  Input errors, so no output created.
Joining the PDF files ...

Creating a folder in Google Drive to upload files 

Folder Name : OCR-চিত্র:গীতি-কবিতা.pdf-temp-2016-01-01-01-15-12

Traceback (most recent call last):
  File "/usr/local/bin/gdmkdir.py", line 10, in <module>
    from gdcmdtools.mkdir import GDMkdir
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/mkdir.py", line 19, in <module>
    from gdcmdtools.base import GDBase
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/base.py", line 7, in <module>
    from apiclient.discovery import build
  File "/usr/local/lib/python2.7/dist-packages/apiclient/**init**.py", line 1, in <module>
    from .base import APIClient, APIClient_SharedSecret
  File "/usr/local/lib/python2.7/dist-packages/apiclient/base.py", line 3, in <module>
    from urllib3 import connection_from_url
ImportError: No module named urllib3

Moving all temp files to OCR-চিত্র:গীতি-কবিতা.pdf-temp-2016-01-01-01-15-12

Traceback (most recent call last):
  File "do_ocr.py", line 240, in <module>
    os.system(command)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 68-72: ordinal not in range(128)

**Comment by tshrinivasan** [comment]
mutool is not installed.

Install it

**Comment by jayantanth** [comment]
After install Mutool, the following error ......................

pdfunite version 0.18.4
Copyright 2005-2011 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2004 Glyph & Cog, LLC
Usage: pdfunite [options] <PDF-sourcefile-1>..<PDF-sourcefile-n> <PDF-destfile>
  -v             : print copyright and version info
  -h             : print usage information
  -help          : print usage information
  --help         : print usage information
  -?             : print usage information

Creating a folder in Google Drive to upload files 

Folder Name : OCR-গীতি-কবিতা.pdf-temp-2016-01-02-20-54-09

Traceback (most recent call last):
  File "/usr/local/bin/gdmkdir.py", line 10, in <module>
    from gdcmdtools.mkdir import GDMkdir
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/mkdir.py", line 19, in <module>
    from gdcmdtools.base import GDBase
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/base.py", line 7, in <module>
    from apiclient.discovery import build
  File "/usr/local/lib/python2.7/dist-packages/apiclient/**init**.py", line 1, in <module>
    from .base import APIClient, APIClient_SharedSecret
  File "/usr/local/lib/python2.7/dist-packages/apiclient/base.py", line 3, in <module>
    from urllib3 import connection_from_url
ImportError: No module named urllib3

Moving all temp files to OCR-গীতি-কবিতা.pdf-temp-2016-01-02-20-54-09

Traceback (most recent call last):
  File "do_ocr.py", line 240, in <module>
    os.system(command)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 68-71: ordinal not in range(128)

**Comment by jayantanth** [comment]
I can see that all PDF page converted to myHDD  \home\OCR

**Comment by ravidreams** [comment]
Same error reported here - https://github.com/tshrinivasan/OCR4wikisource/issues/8

This thread can be closed as the same bug is addressed in two threads.

**Comment by tshrinivasan** [comment]
Closing this.
