### ISSUE TITLE
mediawiki-uploader.py is failing to upload to every 10th page

### ISSUE THREAD

**Issue by omshivaprakash** [tshrinivasan/OCR4wikisource#2]
you can see that it didn't upload content for 30th and 40th page here. 
https://kn.wikisource.org/wiki/%E0%B2%AA%E0%B2%B0%E0%B2%BF%E0%B2%B5%E0%B2%BF%E0%B2%A1%E0%B2%BF:Duurada_Nakshhatra.pdf

Anything to do with the following in indian_numerals.ini?
0 = ೦     

Good to see that the script won't upload to existing pages.

**Comment by omshivaprakash** [comment]
I was expecting this issue - https://kn.wikisource.org/wiki/%E0%B2%AA%E0%B3%81%E0%B2%9F:Duurada_Nakshhatra.pdf/%E0%B3%AE%E0%B3%A8 - this page contains the text of ೮೫ (85)th page. 
It means 3 pages didn't get uploaded.

**Comment by tshrinivasan** [comment]
Fixed the issues with 10,20,30,40 etc page no.

Pull and test again.
