### ISSUE TITLE
Handling line breaks

### ISSUE THREAD

**Issue by ravidreams** [tshrinivasan/OCR4wikisource#23]
Hi, 

I am attaching a text file and pdf page file generated after do_ocr.py

The line breaks are not accurate. 

Even while doing a manual upload and checking in Google drive, the line breaks are not accurate. But, I guess we are losing even more line breaks while we create the text file. 

More comments welcome from bn community. 

Attaching two sample files. 
[page_00014.pdf](https://github.com/tshrinivasan/OCR4wikisource/files/78086/page_00014.pdf)
[text_for_page_00014.txt](https://github.com/tshrinivasan/OCR4wikisource/files/78087/text_for_page_00014.txt)
[text_for_page_00015.txt](https://github.com/tshrinivasan/OCR4wikisource/files/78088/text_for_page_00015.txt)
[page_00015.pdf](https://github.com/tshrinivasan/OCR4wikisource/files/78089/page_00015.pdf)

**Comment by bodhisattwawiki** [comment]
In Wikisource, we have to proof-read every pages manually. While doing that, we can fix the line breaks easily. I think, its not the issue of Google-OCR and Wikisource Integration. Its an issue of the Google OCR product itself. Still, waiting comments from Jayantada.

**Comment by ravidreams** [comment]
Yes, I am just reporting all issues. Not everything is priority and some can be google drive issues which we can't do anything.

**Comment by tshrinivasan** [comment]
Lines breaks are managed by Google.
We can not do anything,

**Comment by ravidreams** [comment]
Ok, even viewing it in Google drive showed different line breaks based on font size. Let us close this thread.
