### ISSUE TITLE
V1.35 Error: No file uploaded to Google drive

### ISSUE THREAD

**Issue by jayantanth** [tshrinivasan/OCR4wikisource#28]
Using latest version script : 
After spliting PDF not file uploaded in GD and download OCRed text file...............

Copyright 2005-2011 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2004 Glyph & Cog, LLC
Usage: pdfunite [options] <PDF-sourcefile-1>..<PDF-sourcefile-n> <PDF-destfile>
  -v             : print copyright and version info
  -h             : print usage information
  -help          : print usage information
  --help         : print usage information
  -?             : print usage information
INFO:**main**:
Creating a folder in Google Drive to upload files. Folder Name : OCR-রাসেলাস.djvu-temp-2016-01-13-20-16-43

INFO:**main**:Running gdmkdir.py OCR-রাসেলাস.djvu-temp-2016-01-13-20-16-43 | tee folder_in_google_drive.log
id: 0B1OpcVV-_vRSMDh0MHZmXy1xVDQ
drive view: https://drive.google.com/drive/folders/0B1OpcVV-_vRSMDh0MHZmXy1xVDQ
folder view: https://docs.google.com/folderview?id=0B1OpcVV-_vRSMDh0MHZmXy1xVDQ&usp=drivesdk
[]
INFO:__main__:Split the text files to sync with the original images
INFO:**main**:Joining text files based on Column No
INFO:**main**:
Moving all temp files to OCR-রাসেলাস.djvu-temp-2016-01-13-20-16-43

INFO:**main**:Running mv folder_.log currentfile.pdf  doc_data.txt pg_.pdf page\* txt\*  _.uploadOCR-রাসেলাস.djvu-temp-2016-01-13-20-16-43
mv: target `_.uploadOCR-রাসেলাস.djvu-temp-2016-01-13-20-16-43' is not a directory
INFO:**main**:

Done. Check the text files start with text_for_page_ 

[do_ocr_2016-01-13-20-16-43_log.txt](https://github.com/tshrinivasan/OCR4wikisource/files/89029/do_ocr_2016-01-13-20-16-43_log.txt)

**Comment by tshrinivasan** [comment]
Fixed it at version 1.36

Check and update.

**Comment by jayantanth** [comment]
Now in V1.36 working fine. :+1:

**Comment by tshrinivasan** [comment]
Thanks. Closing this.
