### ISSUE TITLE
PDF file name with brackets facing syntex error.

### ISSUE THREAD

**Issue by tha-uzhavan** [tshrinivasan/OCR4wikisource#30]
we often use brackets for differentiate files in  Disambiguation
https://ta.wikipedia.org/s/tih
When i try to convert the below file to OCR,  facing syntex error.
https://commons.wikimedia.org/wiki/File:%E0%AE%9A%E0%AF%87%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AE%BF%E0%AE%B4%E0%AE%BE%E0%AE%B0%E0%AF%8D_%28%E0%AE%86%E0%AE%B0%E0%AE%BE%E0%AE%AF%E0%AF%8D%E0%AE%9A%E0%AF%8D%E0%AE%9A%E0%AE%BF_%E0%AE%A8%E0%AF%82%E0%AE%B2%E0%AF%8D%29.pdf

**Comment by jayantanth** [comment]
Duplicate #26

**Comment by tha-uzhavan** [comment]
​ என்னால் எதுவும் செய்ய இயலவில்லை. புரியவில்லை.

-_தகவலுழவன்_
Wikimedia-User-Name:\* Info-farmer  _Mobile:_+91 9095343342*

**Comment by tshrinivasan** [comment]
Bracket in filename issue is solved already.

Get latest version and run.
