### ISSUE TITLE
Proposal:add edit summery at mediawiki_uploader.py  "OCR added"

### ISSUE THREAD

**Issue by jayantanth** [tshrinivasan/OCR4wikisource#31]
Please add the edit summery as default to mediawiki_uploader.py  "OCR added"

**Comment by tshrinivasan** [comment]
What is the content to be added along with the text to add the edit summary?

is there any wiki syntax for this?

**Comment by jayantanth** [comment]
Here some example for python https://www.mediawiki.org/wiki/API:Edit/Editing_with_Python

**Comment by tshrinivasan** [comment]
Added a parameter in config.ini as edit_summary in version 1.39

Fill that and run mediawiki_uploader.py

**Comment by jayantanth** [comment]
Thanks , edit summery added successfully :+1:
