### ISSUE TITLE
File name with apostrophe makes syntex error

### ISSUE THREAD

**Issue by tha-uzhavan** [tshrinivasan/OCR4wikisource#39]
I tried to do OCR with the following 'apostrophe-file names'. 
https://commons.wikimedia.org/wiki/File:Sahadeva's_Stratagem.pdf
https://commons.wikimedia.org/wiki/File:The_surgeon_general's_prescription_and_vichu's_wife.pdf
But unable to do so.

**Comment by tshrinivasan** [comment]
Fixed this in version 1.43
