### ISSUE TITLE
Temp Folder

### ISSUE THREAD

**Issue by tshrinivasan** [tshrinivasan/OCR4wikisource#4]
Please do create a temporary folder for the PDF downloads and split operations before hand so that it won't make the working folder crowded. Also, book file name itself can be used as the working folder name.

by @omshivaprakash

**Comment by ravidreams** [comment]
The same needs to be done in Google Drive too. All temp folders need to be put under a folder called OCR4wikisource to avoid the root folder getting crowded with temp folders. Especially when we do lot of testing. Om's suggestion makes sense too as we can also make these folders shared for public viewing.

**Comment by tshrinivasan** [comment]
We can create many folders with same name in google drive.
Its being tough to create one single parent folder and many subfolders for OCR.

Bur creating the temp folders as "OCR" + filename + "temp" + timestamp
