### ISSUE TITLE
Shall we run mediawiki_uploader.py after do_ocr.py, automatically?

### ISSUE THREAD

**Issue by tshrinivasan** [tshrinivasan/OCR4wikisource#45]
Shall we run mediawiki_uploader.py after do_ocr.py, automatically?

if there is no error displayed by do_ocr.py, i think we can run the mediawiki_uploader.py automatically.

share your thoughts.

@jayantanth @BodhisattwaMandal @omshivaprakash @ravidreams @tha-uzhavan

**Comment by jayantanth** [comment]
Yap :-) if do_ocr.py done completely, then it could be done.
