### ISSUE TITLE
archives name 

### ISSUE THREAD

**Issue by tha-uzhavan** [tshrinivasan/OCR4wikisource#50]
If possible, kindly rename the archives name with file name like text-for-**file_name**.pdf

**Comment by tshrinivasan** [comment]
That is common name.

All books go inside it.

Check the folders inside archives.

**Comment by tha-uzhavan** [comment]
yes,   inside  all are perfect.  I asked with the proof readers thoughts.  To avoid human errors. Instead of archives, if it is like, for example,  files-for-உரிமைப்_பெண்.pdf.  It is a thought not a need. I shared it with you.

**Comment by tshrinivasan** [comment]
fixed this
