### ISSUE TITLE
wikitools.api.APIError

### ISSUE THREAD

**Issue by jayantanth** [tshrinivasan/OCR4wikisource#51]
INFO:root:=========
INFO:root:Moving the file text_for_page_00026.txt to the folder upload-বিশ্বকোষ_তৃতীয়_খণ্ড.djvu-2016-02-12-23-23-03

INFO:root:Filename = বিশ্বকোষ_তৃতীয়_খণ্ড.djvu
INFO:root:Indic page no = ২৭
INFO:root:Page name = বিশ্বকোষ_তৃতীয়_খণ্ড.djvu/২৭
INFO:root:
Uploading content for text_for_page_00027.txt
Traceback (most recent call last):
  File "mediawiki_uploader.py", line 224, in <module>
    page.edit(text=content,summary=edit_summary,bot="True")
  File "/usr/local/lib/python2.7/dist-packages/wikitools/page.py", line 623, in edit
    result = req.query()
  File "/usr/local/lib/python2.7/dist-packages/wikitools/api.py", line 165, in query
    raise APIError(data['error']['code'], data['error']['info'])
wikitools.api.APIError: (u'readonly', u'The wiki is currently in read-only mode')

**Comment by tshrinivasan** [comment]
Interesting error.

"The wiki is currently in read-only mode"

How can a wiki become read only?

Are you running with a BOT account?

is this caused by very fast frequent writing via API?

**Comment by jayantanth** [comment]
The job is completed successfully, after re-run mediawiki_uploader.py . I have just reported the bug.

**Comment by jayantanth** [comment]
Have found one bug https://phabricator.wikimedia.org/T67228
