### ISSUE TITLE
Contributions are not reflecting in wikisource

### ISSUE THREAD

**Issue by commonssibi** [tshrinivasan/OCR4wikisource#53]
I  run the do_ocr.py with the following in the config.ini file .

```
file_url = https://upload.wikimedia.org/wikipedia/commons/8/80/The_surgeon_general%27s_prescription_and_vichu%27s_wife.pdf
columns = 1
wiki_username = Commons sibiBOT
wiki_password = *********************************
wikisource_language_code = ta
keep_temp_folder_in_google_drive = no
edit_summary = Text from Google OCR
```

Also while running the do_ocr , I get the following screen 

![1](https://cloud.githubusercontent.com/assets/5329404/13026122/f9ae9a16-d242-11e5-9572-19d6975418c3.png)

And everything goes well .
![2](https://cloud.githubusercontent.com/assets/5329404/13026124/18e9b6b8-d243-11e5-9f9c-ff904c76b9d0.png)

But ,  I am not able to see my contributions .
https://ta.wikisource.org/wiki/%E0%AE%9A%E0%AE%BF%E0%AE%B1%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%81:Contributions/Commons_sibiBOT

or 

https://ta.wikisource.org/wiki/%E0%AE%9A%E0%AE%BF%E0%AE%B1%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%81:ListFiles/Commons_sibiBOT

What would be the reason :(

**Comment by tshrinivasan** [comment]
Do you see the uploaded files in relevant wiki source pages?

Share the log for mediawiki uploader.

**Comment by ravidreams** [comment]
This issue can be closed. Sibi was trying to upload an already uploaded book. Filed a separate issue for this - https://github.com/tshrinivasan/OCR4wikisource/issues/56
