### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Sujay77** [tshrinivasan/OCR4wikisource#54]
Hi,
I am trying to install OCR4wikisource. My OS is UBUNTU 14.10.
After installation these message is showing...
"W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/utopic-backports/universe/binary-amd64/Packages  404  Not Found [IP: 91.189.92.200 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/utopic-backports/multiverse/binary-amd64/Packages  404  Not Found [IP: 91.189.92.200 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/utopic-backports/main/binary-i386/Packages  404  Not Found [IP: 91.189.92.200 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/utopic-backports/restricted/binary-i386/Packages  404  Not Found [IP: 91.189.92.200 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/utopic-backports/universe/binary-i386/Packages  404  Not Found [IP: 91.189.92.200 80]

W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/utopic-backports/multiverse/binary-i386/Packages  404  Not Found [IP: 91.189.92.200 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Unable to locate package mupdf-tools"

**Comment by nasirkhan** [comment]
If you are sure that you internet connection was ok. then please try to change the archive form India to Main and try to install the packages again. It might solve your issues.

**Comment by tshrinivasan** [comment]
run

sudo apt-get update

first.

try the solution given by @nasirkhan 
Closing this for now.

comment here, if you still has issues.
