### ISSUE TITLE
Make logging optional

### ISSUE THREAD

**Issue by srikanthlogic** [tshrinivasan/OCR4wikisource#57]
Logging can be enabled with config option. This will improve speed of script

**Comment by ravidreams** [comment]
+1

**Comment by jayantanth** [comment]
How exactly it will be? Any example?

**Comment by ravidreams** [comment]
Config.ini will have an option like

Logging = No

Shrini introduced the logging feature to help in troubleshooting. Now that the tool is stable, it can be disabled by users who are well introduced to the tool.  Shrini felt that the logging delays processing only be microseconds. But still, if it can help to increase the speed by anyway, it is good.

**Comment by tshrinivasan** [comment]
Logging is very important feature for any application.

Though the application is stable now, it is growing with more new features.

I dont find any reason to disable it and it wont save more than few seconds.

Let the logging be there.
