### ISSUE TITLE
Option to remove temp files in Google Drive

### ISSUE THREAD

**Issue by ravidreams** [tshrinivasan/OCR4wikisource#6]
I am just sharing my thoughts. Feel free to ignore if this is lot of work or just bloat the program. 

I expect a use case where only a few users will run this tool for bulk of the uploads in their languages. But, google drive storage is limited. You may add an option in config.ini which will allow the users to remove the temp files automatically.

**Comment by tshrinivasan** [comment]
Completed this.
Provided an option in config.ini
keep_temp_folder_in_google_drive = yes or no
