### ISSUE TITLE
Internal Error 500 while uploading to Google

### ISSUE THREAD

**Issue by nasirkhan** [tshrinivasan/OCR4wikisource#72]
Getting the following error at the time of working on the following book. This error is showing for each page. 

https://bn.wikisource.org/wiki/%E0%A6%A8%E0%A6%BF%E0%A6%B0%E0%A7%8D%E0%A6%98%E0%A6%A3%E0%A7%8D%E0%A6%9F:%E0%A6%AC%E0%A6%BE%E0%A6%99%E0%A7%8D%E0%A6%97%E0%A6%B2%E0%A6%BE%E0%A6%B0_%E0%A6%87%E0%A6%A4%E0%A6%BF%E0%A6%B9%E0%A6%BE%E0%A6%B8-%E0%A6%85%E0%A6%B7%E0%A7%8D%E0%A6%9F%E0%A6%BE%E0%A6%A6%E0%A6%B6_%E0%A6%B6%E0%A6%A4%E0%A6%BE%E0%A6%AC%E0%A7%8D%E0%A6%A6%E0%A7%80-%E0%A6%A8%E0%A6%AC%E0%A6%BE%E0%A6%AC%E0%A7%80_%E0%A6%86%E0%A6%AE%E0%A6%B2.pdf

Direct URL: https://upload.wikimedia.org/wikipedia/commons/4/46/%E0%A6%AC%E0%A6%BE%E0%A6%99%E0%A7%8D%E0%A6%97%E0%A6%B2%E0%A6%BE%E0%A6%B0_%E0%A6%87%E0%A6%A4%E0%A6%BF%E0%A6%B9%E0%A6%BE%E0%A6%B8-%E0%A6%85%E0%A6%B7%E0%A7%8D%E0%A6%9F%E0%A6%BE%E0%A6%A6%E0%A6%B6_%E0%A6%B6%E0%A6%A4%E0%A6%BE%E0%A6%AC%E0%A7%8D%E0%A6%A6%E0%A7%80-%E0%A6%A8%E0%A6%AC%E0%A6%BE%E0%A6%AC%E0%A7%80_%E0%A6%86%E0%A6%AE%E0%A6%B2.pdf

```
INFO:__main__:

uploading page_00002.pdf to google Drive. 
INFO:__main__:Running gdput.py -t ocr -f   0Bzu8oam42f2mWi1qazc3aUhHU1E page_00002.pdf | tee page_00002.log
Uploading file: page_00002.pdf
File size: 5.0KB
Traceback (most recent call last):
  File "/usr/local/bin/gdput.py", line 252, in <module>
    response = puter.run()
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/put.py", line 120, in run
    result = getattr(self, self.target_type + "_put")()
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/put.py", line 505, in ocr_put
    return self.generic_put(True)
  File "/usr/local/lib/python2.7/dist-packages/gdcmdtools/put.py", line 485, in generic_put
    service_response = request.execute()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 729, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 500 when requesting https://www.googleapis.com/upload/drive/v2/files?uploadType=multipart&convert=true&alt=json returned "Internal Error">
INFO:__main__:
```

**Comment by tshrinivasan** [comment]
give the direct url of the file.
the one you is not direct url of the file.

## 

Regards,
T.Shrinivasan

My Life with GNU/Linux : http://goinggnu.wordpress.com
Free E-Magazine on Free Open Source Software in Tamil : http://kaniyam.com

Get Free Tamil Ebooks for Android, iOS, Kindle, Computer :
http://FreeTamilEbooks.com

**Comment by nasirkhan** [comment]
https://upload.wikimedia.org/wikipedia/commons/4/46/%E0%A6%AC%E0%A6%BE%E0%A6%99%E0%A7%8D%E0%A6%97%E0%A6%B2%E0%A6%BE%E0%A6%B0_%E0%A6%87%E0%A6%A4%E0%A6%BF%E0%A6%B9%E0%A6%BE%E0%A6%B8-%E0%A6%85%E0%A6%B7%E0%A7%8D%E0%A6%9F%E0%A6%BE%E0%A6%A6%E0%A6%B6_%E0%A6%B6%E0%A6%A4%E0%A6%BE%E0%A6%AC%E0%A7%8D%E0%A6%A6%E0%A7%80-%E0%A6%A8%E0%A6%AC%E0%A6%BE%E0%A6%AC%E0%A7%80_%E0%A6%86%E0%A6%AE%E0%A6%B2.pdf

**Comment by jayantanth** [comment]
quite similar #9

**Comment by nasirkhan** [comment]
@tshrinivasan did you find any clue? 
facing the same issue for https://upload.wikimedia.org/wikipedia/commons/5/5c/%E0%A6%97%E0%A7%8B%E0%A6%AA%E0%A7%80%E0%A6%9A%E0%A6%A8%E0%A7%8D%E0%A6%A6%E0%A7%8D%E0%A6%B0%E0%A7%87%E0%A6%B0_%E0%A6%97%E0%A6%BE%E0%A6%A8.pdf

**Comment by tshrinivasan** [comment]
reported here - https://github.com/tienfuc/gdcmdtools/issues/95

**Comment by tshrinivasan** [comment]
This is internal error of google.
as we can not do anything on this, closing this.

Hope we can add some dummy text files instead of the error file.

#79 also talks this.
Will check the dummy files option.
