### ISSUE TITLE
Planning to extend it to a Wordpress upload 

### ISSUE THREAD

**Issue by commonssibi** [tshrinivasan/OCR4wikisource#73]
Enhancement : 
I am planning to work on an enhancement to extend the current wikisource specific stuff to Wordpress . Possible applications which I see are 
1)Personalised testing for pages from "copyrighted" books which cannot be uploaded to wikicommons for testing .
2)Languague Computing test Data which could be evolved .

**Comment by jayantanth** [comment]
@commonssibi  this is only for specific to wikisource.

**Comment by commonssibi** [comment]
@jayantanth  . As mentioned above this is a enhancement/fork which I am planning to take up . Without affecting any of the coding or merges to the current project .

**Comment by tshrinivasan** [comment]
closing this as this is not related to wikisource.

@commonssibi  interested to see the wordpress fork.

This can be useful.
https://github.com/tshrinivasan/odt2wordpress
