### ISSUE TITLE
Unicode encode error

### ISSUE THREAD

**Issue by ravidreams** [tshrinivasan/OCR4wikisource#8]
URL - https://upload.wikimedia.org/wikipedia/commons/4/44/%E0%A6%97%E0%A7%80%E0%A6%A4%E0%A6%BF-%E0%A6%95%E0%A6%AC%E0%A6%BF%E0%A6%A4%E0%A6%BE.pdf

WS Index location - https://bn.wikisource.org/wiki/%E0%A6%A8%E0%A6%BF%E0%A6%B0%E0%A7%8D%E0%A6%98%E0%A6%A3%E0%A7%8D%E0%A6%9F:%E0%A6%97%E0%A7%80%E0%A6%A4%E0%A6%BF-%E0%A6%95%E0%A6%AC%E0%A6%BF%E0%A6%A4%E0%A6%BE.pdf

PDF was downloaded and available in system as single page pdf files. But, upload to Google didn't happen.

Error log:

Moving all temp files to OCR-গীতি-কবিতা.pdf-temp-2015-12-28-21-34-33

Traceback (most recent call last):
  File "do_ocr.py", line 240, in <module>
    os.system(command)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 68-71: ordinal not in range(128)

**Comment by ravidreams** [comment]
Same error for this file too - https://upload.wikimedia.org/wikipedia/commons/4/43/%E0%A6%AE%E0%A7%87%E0%A6%98%E0%A6%A8%E0%A6%BE%E0%A6%A6%E0%A6%AC%E0%A6%A7_%E0%A6%95%E0%A6%BE%E0%A6%AC%E0%A7%8D%E0%A6%AF.pdf

**Comment by jayantanth** [comment]
Thank Ravi, Yahaa, you have reported...

**Comment by tshrinivasan** [comment]
I think it is fixed already.

The reported files are uploading to google drive in my system.

As the commits are happening rapidly, always use the latest version before running.

Added a file VERSION to compare your version and the latest version.

Compare it and run git pull before running the do_ocr.py

Check now and share the results.

**Comment by ravidreams** [comment]
encoding error gone. but now stuck with https://github.com/tshrinivasan/OCR4wikisource/issues/10

**Comment by tshrinivasan** [comment]
Fixed #10 also.

Closing this.
