### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by manojkmohan** [tshrinivasan/OCR4wikisource#81]
Hi.
I am Experimenting the tool for Malayalam Wikisource and its giving some errors. https://jpst.it/GdnC

**Comment by tshrinivasan** [comment]
it seems the djvu file is not converted to pdf.

run the following command and check if the pdf conversion works well.

ddjvu --format=pdf "പ്രമാണം:Test.djvu"   "പ്രമാണം:Test".pdf

share the results.

**Comment by tshrinivasan** [comment]
closing as no response.
