### ISSUE TITLE
The 10 page limit supposed in the README.MD TODO may no longer hold.

### ISSUE THREAD

**Issue by vvasuki** [tshrinivasan/OCR4wikisource#82]
Hello!

Greetings from the [sanskrit OCR project](https://sites.google.com/site/sanskritcode/ocr/1-ocr-ing), and thanks for this wonderful utility (which I haven't tried yet, but am eager to) ! The TODO in the [README.md](https://github.com/tshrinivasan/OCR4wikisource/blob/master/README.md) assumes that Google Drive can only do 10 pages, but [recent tests](https://groups.google.com/d/msg/sanskrit-programmers/5noVN-XpeVY/LtO61wPUCQAJ) indicate otherwise.

**Comment by jayantanth** [comment]
As of now this is not to be fix for 10 page limit, because this script upload page one by one, so there is no limitation of 10 page. So this is not needed at all.

**Comment by bodhisattwawiki** [comment]
This issue can be closed. It is not an issue anymore.
