### ISSUE TITLE
Setup instructions outdated, gdauth failing.

### ISSUE THREAD

**Issue by vvasuki** [tshrinivasan/OCR4wikisource#84]
Two problems:
1. Setup instructions are out of date - API manager webpage seems to have a new UI. 
   ![image](https://cloud.githubusercontent.com/assets/2664797/14450803/80edbc7a-0036-11e6-900b-bb58f671bfa6.png) That needs to be fixed.
2. But I guessed along and downloaded a json file just fine. The "gdauth.py client_secrets.json" setup step is failing:
   
   > gdauth.py ~/Downloads/sanskritnlp-fab6860d4668.json 
   > ERROR:gdcmdtools.auth:storage_file: /home/vvasuki/.gdcmdtools.creds not exists
   > ERROR:gdcmdtools.auth:failed on flow_from_clientsecrets()
   > Failed to pass OAuth2 authentication

EDIT: Created an issue [here as well](https://github.com/tienfuc/gdcmdtools/issues/97).

**Comment by tshrinivasan** [comment]
@vvasuki is the issue still happening?

yes, as you said, the UI of google is always changing.

do you still having the gdauth issue?

Closing this for now.

comment here if you have any issues.
