### ISSUE TITLE
Needed to install python package seperately on Ubuntu 16.04

### ISSUE THREAD

**Issue by nasirkhan** [tshrinivasan/OCR4wikisource#85]
I am running the script from Ubuntu 16.04 where everything work installed properly but i asked to install the following packages separately. If the you are facing this issue use the command mentioned bellow to install the packages.

```
clint
wikitools
poster
```

`pip install clint wikitools poster`

Install MuPDF

```
sudo add-apt-repository ppa:ubuntuhandbook1/apps
sudo apt-get update
sudo apt-get install mupdf mupdf-tools

```

Install pdftk
`sudo apt-get install pdftk`

Install djview
`sudo apt-get install djview djvulibre-bin`

**Comment by tshrinivasan** [comment]
added this in setup.sh file.

check it.
