### ISSUE TITLE
Language not being recgonized

### ISSUE THREAD

**Issue by satdeepgill** [tshrinivasan/OCR4wikisource#90]
Hi, I have tried using this tool for Punjabi (Gurmukhi) text on Multilingual Wikisource but the OCR was unable to recognize the text. On the other hand, if i upload the image on Google Drive then it is able to recognize by itself.

Check here: https://wikisource.org/wiki/Page:Sample_OCR.pdf/1

**Comment by tshrinivasan** [comment]
@satdeepgill 
can you share the link for a sample PDF in Gurmukhi language.
Will check it.

**Comment by tshrinivasan** [comment]
provided a new file here
https://github.com/tshrinivasan/OCR4wikisource/issues/99#issuecomment-389474388

hope this fixes the issue.

reopen or comment on the same #99 if you still getting the same issue.
