### ISSUE TITLE
Add Devanagari numerals for Marathi Wikisource

### ISSUE THREAD

**Issue by bodhisattwawiki** [tshrinivasan/OCR4wikisource#91]
[mr]

0 = ०
1 = १
2 = २
3 = ३
4 = ४
5 = ५
6 = ६
7 = ७
8 = ८
9 = ९

**Comment by jayantanth** [comment]
Just advice , Who will run this script, add the above to indian_numerals.ini file.

**Comment by bodhisattwawiki** [comment]
@jayantanth, I have already add the above lines to the local computer indian_numerals.ini file. Now only 1 person will be doing the OCR in mr ws. But the pull request is for other users who want to install it in other computers later

**Comment by tshrinivasan** [comment]
Merged the pull request for this.
Thanks.
